name: hello-world
on:
  push:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v2
        run: ci/build-app.sh